# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ABLY-iOS' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ABLY-iOS

  pod 'SnapKit', '~> 5.0.0'
  pod 'Alamofire', '~> 5.2'
  pod 'AlamofireNetworkActivityLogger', '~> 3.4'

end
